

const budgetValue = 2800
export const allDestinations = [
    {
        id: 1,
        country: "France",
        city: "Paris",
        title: "Paris, France",
        subtitle: "The City of Light - Perfect for culture and cuisine lovers",
        price: Math.round(budgetValue * 0.95),
        originalPrice: budgetValue,
        savings: Math.round(budgetValue * 0.05),
        rating: 4.8,
        reviews: 2847,
        matchScore: 95,
        flightTime: "7-9 hours from most locations",
        highlights: [
            "Louvre & Musée d'Orsay priority access",
            "Seine river dinner cruise",
            "Montmartre artist quarter exploration",
            "French cooking class with chef",
            "Historic Latin Quarter walking tour",
        ],
        whyMatch: "Perfect for History & Culture + Food & Dining interests",
        bestFor: ["History", "Food", "Arts"],
        climate: "Mild summer, perfect for walking tours",
        currency: "Euro (EUR)",
        language: "French (English widely spoken in tourist areas)",
        image: "/placeholder.svg?height=200&width=300",
        flag: "🇫🇷",
    },
    {
        id: 2,
        country: "Italy",
        city: "Rome",
        title: "Rome, Italy",
        subtitle: "Eternal City - Where history comes alive",
        price: Math.round(budgetValue * 0.88),
        originalPrice: budgetValue,
        savings: Math.round(budgetValue * 0.12),
        rating: 4.9,
        reviews: 3156,
        matchScore: 92,
        flightTime: "8-12 hours from most locations",
        highlights: [
            "Colosseum & Roman Forum guided tours",
            "Vatican Museums & Sistine Chapel",
            "Traditional Roman food tour",
            "Trastevere neighborhood exploration",
            "Cooking class: Pasta & Gelato making",
        ],
        whyMatch: "Exceptional for History & Culture with amazing Food & Dining",
        bestFor: ["History", "Food", "Arts"],
        climate: "Warm and sunny, ideal for sightseeing",
        currency: "Euro (EUR)",
        language: "Italian (English spoken in tourist areas)",
        image: "/placeholder.svg?height=200&width=300",
        flag: "🇮🇹",
    },
    {
        id: 3,
        country: "Japan",
        city: "Tokyo",
        title: "Tokyo, Japan",
        subtitle: "Modern metropolis meets ancient traditions",
        price: Math.round(budgetValue * 1.05),
        originalPrice: Math.round(budgetValue * 1.15),
        savings: Math.round(budgetValue * 0.1),
        rating: 4.9,
        reviews: 1923,
        matchScore: 88,
        flightTime: "11-14 hours from most locations",
        highlights: [
            "Traditional temples & modern districts",
            "Sushi making class with master chef",
            "Shibuya & Harajuku cultural exploration",
            "Traditional tea ceremony experience",
            "Tsukiji fish market food tour",
        ],
        whyMatch: "Unique blend of culture, history, and incredible cuisine",
        bestFor: ["Food", "History", "Arts"],
        climate: "Pleasant summer weather",
        currency: "Japanese Yen (JPY)",
        language: "Japanese (English signage in tourist areas)",
        image: "/placeholder.svg?height=200&width=300",
        flag: "🇯🇵",
    },
    {
        id: 4,
        country: "Spain",
        city: "Barcelona",
        title: "Barcelona, Spain",
        subtitle: "Vibrant city with stunning architecture and beaches",
        price: Math.round(budgetValue * 0.85),
        originalPrice: budgetValue,
        savings: Math.round(budgetValue * 0.15),
        rating: 4.7,
        reviews: 2654,
        matchScore: 90,
        flightTime: "6-10 hours from most locations",
        highlights: [
            "Sagrada Familia and Gaudí architecture",
            "Park Güell and Gothic Quarter",
            "Tapas tours and local markets",
            "Beach relaxation at Barceloneta",
            "Flamenco shows and nightlife",
        ],
        whyMatch: "Perfect blend of culture, food, and relaxation",
        bestFor: ["Arts", "Food", "History"],
        climate: "Mediterranean climate with warm summers",
        currency: "Euro (EUR)",
        language: "Spanish/Catalan (English spoken in tourist areas)",
        image: "/placeholder.svg?height=200&width=300",
        flag: "🇪🇸",
    },
    {
        id: 5,
        country: "Greece",
        city: "Athens",
        title: "Athens, Greece",
        subtitle: "Cradle of civilization with ancient wonders",
        price: Math.round(budgetValue * 0.8),
        originalPrice: budgetValue,
        savings: Math.round(budgetValue * 0.2),
        rating: 4.6,
        reviews: 2156,
        matchScore: 87,
        flightTime: "8-12 hours from most locations",
        highlights: [
            "Acropolis and Parthenon tours",
            "Ancient Agora and archaeological sites",
            "Traditional Greek tavernas",
            "Day trip to nearby islands",
            "National Archaeological Museum",
        ],
        whyMatch: "Rich ancient history and Mediterranean culture",
        bestFor: ["History", "Food", "Arts"],
        climate: "Warm Mediterranean climate",
        currency: "Euro (EUR)",
        language: "Greek (English spoken in tourist areas)",
        image: "/placeholder.svg?height=200&width=300",
        flag: "🇬🇷",
    },
];


export const POPULAR_DESTINATIONS = [
    {id: "1", name: "Paris", country: "France", flag: "🇫🇷"},
    {id: "2", name: "Tokyo", country: "Japan", flag: "🇯🇵"},
];

export const schedule =  [
    // Day 1 - Arrival
    {
        dayNumber: 1,
        date: "Monday, July 15, 2024",
        title: "Welcome to Paris",
        weather: { temperature: "24°C / 75°F", condition: "Sunny", recommendation: "Perfect weather for walking" },
        budget: { total: 500, meals: 200, activities: 200, transport: 100 },
        activities: [
            {
                time: "10:00 AM",
                title: "Arrive at Charles de Gaulle Airport",
                description: "Flight arrival from New York JFK",
                type: "transport",
                duration: "2 hours",
                location: "CDG Airport, Terminal 2E",
                tips: "Collect luggage and proceed to RER B train for city transfer",
            },
            {
                time: "12:30 PM",
                title: "Airport to City Center",
                description: "RER B train to Châtelet-Les Halles, then Metro to hotel",
                type: "transport",
                duration: "1 hour",
                location: "En route to 4th Arrondissement",
                tips: "Buy a weekly Navigo pass for unlimited metro/bus travel",
            },
            {
                time: "2:00 PM",
                title: "Check-in at Hotel des Grands Boulevards",
                description: "Boutique hotel in the heart of Paris",
                type: "accommodation",
                duration: "45 minutes",
                location: "17 Boulevard Poissonnière, 2nd Arrondissement",
                tips: "Ask reception for restaurant recommendations and metro maps",
            },
            {
                time: "3:30 PM",
                title: "Welcome Lunch at L'Ami Jean",
                description: "First taste of authentic Parisian bistro cuisine",
                type: "dining",
                duration: "1.5 hours",
                location: "27 Rue Malar, 7th Arrondissement",
                tips: "Try the famous côte de bœuf and chocolate soufflé",
            },
            {
                time: "5:30 PM",
                title: "Seine River Walk",
                description: "Gentle stroll along the Seine to get oriented",
                type: "activity",
                duration: "2 hours",
                location: "From Pont Neuf to Île Saint-Louis",
                tips: "Perfect for photos and getting your first Paris impressions",
            },
            {
                time: "8:00 PM",
                title: "Dinner at Le Comptoir du Relais",
                description: "Classic French bistro experience",
                type: "dining",
                duration: "2 hours",
                location: "9 Carrefour de l'Odéon, 6th Arrondissement",
                tips: "No reservations - arrive early or be prepared to wait",
            },
        ],
        tips: [
            "Take it easy on your first day",
            "Stay hydrated during the flight",
            "Keep passport and important documents safe",
        ],
    },
    // Day 2 - Classic Paris
    {
        dayNumber: 2,
        date: "Tuesday, July 16, 2024",
        title: "Iconic Paris Landmarks",
        weather: {
            temperature: "26°C / 79°F",
            condition: "Partly cloudy",
            recommendation: "Great day for outdoor sightseeing",
        },
        budget: { total: 500, meals: 180, activities: 220, transport: 100 },
        activities: [
            {
                time: "8:00 AM",
                title: "Breakfast at Du Pain et des Idées",
                description: "Famous artisanal bakery for fresh pastries",
                type: "dining",
                duration: "45 minutes",
                location: "34 Rue Yves Toudic, 10th Arrondissement",
                tips: "Try the pistachio-cherry escargot and café au lait",
            },
            {
                time: "9:30 AM",
                title: "Louvre Museum - Masterpieces Tour",
                description: "Skip-the-line tour focusing on Mona Lisa, Venus de Milo, and highlights",
                type: "sightseeing",
                duration: "3 hours",
                location: "Rue de Rivoli, 1st Arrondissement",
                tips: "Book timed entry tickets online; wear comfortable shoes",
            },
            {
                time: "1:00 PM",
                title: "Lunch at Loulou Restaurant",
                description: "Chic restaurant in Tuileries Garden",
                type: "dining",
                duration: "1.5 hours",
                location: "107 Rue de Rivoli, Tuileries Garden",
                tips: "Great for people-watching and French cuisine",
            },
            {
                time: "3:00 PM",
                title: "Tuileries Garden & Place Vendôme",
                description: "Stroll through historic gardens and luxury shopping district",
                type: "sightseeing",
                duration: "1.5 hours",
                location: "Tuileries Garden to Place Vendôme",
                tips: "Perfect for photos and window shopping at luxury boutiques",
            },
            {
                time: "5:00 PM",
                title: "Eiffel Tower Visit",
                description: "Ascend to the second floor for panoramic city views",
                type: "sightseeing",
                duration: "2 hours",
                location: "Champ de Mars, 7th Arrondissement",
                tips: "Book elevator tickets in advance; best photos from Trocadéro",
            },
            {
                time: "7:30 PM",
                title: "Seine River Cruise",
                description: "Evening cruise with dinner and city illuminations",
                type: "activity",
                duration: "2 hours",
                location: "Departing from Port de la Bourdonnais",
                tips: "Dress warmly for evening breeze; bring camera for night shots",
            },
        ],
        tips: ["Book museum tickets in advance", "Wear comfortable walking shoes", "Bring a camera for iconic shots"],
    },
    // Day 3 - Art & Culture
    {
        dayNumber: 3,
        date: "Wednesday, July 17, 2024",
        title: "Art & Cultural Immersion",
        weather: {
            temperature: "23°C / 73°F",
            condition: "Light rain",
            recommendation: "Perfect museum weather - bring umbrella",
        },
        budget: { total: 500, meals: 200, activities: 200, transport: 100 },
        activities: [
            {
                time: "8:30 AM",
                title: "Breakfast at Café de Flore",
                description: "Historic café frequented by famous writers and artists",
                type: "dining",
                duration: "1 hour",
                location: "172 Boulevard Saint-Germain, 6th Arrondissement",
                tips: "Order the traditional French breakfast with croissants",
            },
            {
                time: "10:00 AM",
                title: "Musée d'Orsay",
                description: "World's finest collection of Impressionist masterpieces",
                type: "sightseeing",
                duration: "2.5 hours",
                location: "1 Rue de la Légion d'Honneur, 7th Arrondissement",
                tips: "Don't miss Monet's Water Lilies and Van Gogh's self-portraits",
            },
            {
                time: "1:00 PM",
                title: "Lunch at L'Ambassade d'Auvergne",
                description: "Traditional French regional cuisine",
                type: "dining",
                duration: "1.5 hours",
                location: "22 Rue du Grenier Saint-Lazare, 3rd Arrondissement",
                tips: "Try the aligot (cheese and potato dish) and regional wines",
            },
            {
                time: "3:00 PM",
                title: "Marais District Walking Tour",
                description: "Historic Jewish quarter with boutiques and galleries",
                type: "cultural",
                duration: "2 hours",
                location: "Le Marais, 3rd & 4th Arrondissements",
                tips: "Visit Place des Vosges, oldest planned square in Paris",
            },
            {
                time: "5:30 PM",
                title: "Picasso Museum",
                description: "Extensive collection in beautiful 17th-century mansion",
                type: "sightseeing",
                duration: "1.5 hours",
                location: "5 Rue de Thorigny, 3rd Arrondissement",
                tips: "Audio guide recommended for context on Picasso's periods",
            },
            {
                time: "7:30 PM",
                title: "Wine Tasting at Le Mary Celeste",
                description: "Natural wines and small plates in trendy Marais spot",
                type: "dining",
                duration: "2 hours",
                location: "1 Rue Commines, 3rd Arrondissement",
                tips: "Great selection of natural wines and fresh oysters",
            },
        ],
        tips: [
            "Museum pass saves time and money",
            "Marais is great for unique shopping",
            "Try local wine bars for authentic experience",
        ],
    },
    // Day 4 - Montmartre & Sacré-Cœur
    {
        dayNumber: 4,
        date: "Thursday, July 18, 2024",
        title: "Bohemian Montmartre",
        weather: {
            temperature: "25°C / 77°F",
            condition: "Sunny",
            recommendation: "Perfect day for hilltop exploration",
        },
        budget: { total: 500, meals: 190, activities: 210, transport: 100 },
        activities: [
            {
                time: "8:00 AM",
                title: "Breakfast at Pierre Hermé",
                description: "World-famous macarons and pastries",
                type: "dining",
                duration: "45 minutes",
                location: "72 Rue Bonaparte, 6th Arrondissement",
                tips: "Try the Ispahan macaron (rose, raspberry, lychee)",
            },
            {
                time: "9:30 AM",
                title: "Funicular to Montmartre",
                description: "Scenic ride up to the artistic hilltop district",
                type: "transport",
                duration: "30 minutes",
                location: "From Pigalle to Sacré-Cœur",
                tips: "Use your metro pass for the funicular",
            },
            {
                time: "10:00 AM",
                title: "Sacré-Cœur Basilica",
                description: "Stunning white basilica with panoramic Paris views",
                type: "sightseeing",
                duration: "1.5 hours",
                location: "35 Rue du Chevalier de la Barre, 18th Arrondissement",
                tips: "Climb the dome for even better views (extra fee)",
            },
            {
                time: "12:00 PM",
                title: "Montmartre Village Exploration",
                description: "Wander cobblestone streets, artist squares, and cafés",
                type: "cultural",
                duration: "2 hours",
                location: "Place du Tertre and surrounding streets",
                tips: "Watch street artists at work and visit the Moulin Rouge exterior",
            },
            {
                time: "2:30 PM",
                title: "Lunch at La Consigne",
                description: "Cozy bistro with traditional French comfort food",
                type: "dining",
                duration: "1.5 hours",
                location: "16 Rue de la Vieuville, 18th Arrondissement",
                tips: "Try the duck confit and chocolate mousse",
            },
            {
                time: "4:30 PM",
                title: "Musée de Montmartre",
                description: "History of the artistic district and its famous residents",
                type: "sightseeing",
                duration: "1 hour",
                location: "12 Rue Cortot, 18th Arrondissement",
                tips: "Beautiful gardens with vineyard views",
            },
            {
                time: "6:00 PM",
                title: "Sunset at Place du Tertre",
                description: "Watch the sunset over Paris from the artist square",
                type: "activity",
                duration: "1 hour",
                location: "Place du Tertre, 18th Arrondissement",
                tips: "Perfect time for portrait sketches by local artists",
            },
            {
                time: "8:00 PM",
                title: "Dinner at Le Moulin de la Galette",
                description: "Historic windmill restaurant with French cuisine",
                type: "dining",
                duration: "2 hours",
                location: "83 Rue Lepic, 18th Arrondissement",
                tips: "Romantic setting in a converted 17th-century windmill",
            },
        ],
        tips: [
            "Wear comfortable shoes for cobblestone streets",
            "Bring camera for amazing city views",
            "Evening is magical with street lights",
        ],
    },
    // Day 5 - Versailles Day Trip
    {
        dayNumber: 5,
        date: "Friday, July 19, 2024",
        title: "Palace of Versailles",
        weather: { temperature: "27°C / 81°F", condition: "Sunny", recommendation: "Great weather for palace gardens" },
        budget: { total: 500, meals: 170, activities: 230, transport: 100 },
        activities: [
            {
                time: "7:30 AM",
                title: "Early Breakfast at Hotel",
                description: "Quick breakfast before day trip",
                type: "dining",
                duration: "30 minutes",
                location: "Hotel restaurant",
                tips: "Pack snacks and water for the day",
            },
            {
                time: "8:30 AM",
                title: "RER C Train to Versailles",
                description: "Direct train from central Paris to Versailles",
                type: "transport",
                duration: "1 hour",
                location: "From Invalides to Versailles Château",
                tips: "Buy round-trip tickets and validate before boarding",
            },
            {
                time: "10:00 AM",
                title: "Palace of Versailles Tour",
                description: "Opulent royal palace with Hall of Mirrors and State Apartments",
                type: "sightseeing",
                duration: "3 hours",
                location: "Place d'Armes, Versailles",
                tips: "Audio guide essential; avoid crowds by arriving early",
            },
            {
                time: "1:30 PM",
                title: "Lunch at La Petite Venise",
                description: "Restaurant in the palace grounds",
                type: "dining",
                duration: "1 hour",
                location: "Versailles Palace Grounds",
                tips: "Convenient location within the estate",
            },
            {
                time: "3:00 PM",
                title: "Gardens of Versailles",
                description: "Magnificent formal gardens with fountains and groves",
                type: "activity",
                duration: "2.5 hours",
                location: "Versailles Palace Gardens",
                tips: "Rent a bike or golf cart to cover more ground",
            },
            {
                time: "6:00 PM",
                title: "Marie Antoinette's Estate",
                description: "The Queen's private retreat with Petit Trianon",
                type: "sightseeing",
                duration: "1.5 hours",
                location: "Trianon Estate, Versailles",
                tips: "Peaceful contrast to the main palace's grandeur",
            },
            {
                time: "8:00 PM",
                title: "Return to Paris",
                description: "RER C train back to central Paris",
                type: "transport",
                duration: "1 hour",
                location: "Versailles to Paris",
                tips: "Trains run frequently until late evening",
            },
            {
                time: "9:30 PM",
                title: "Late Dinner at L'As du Fallafel",
                description: "Famous falafel in the Marais district",
                type: "dining",
                duration: "45 minutes",
                location: "34 Rue des Rosiers, 4th Arrondissement",
                tips: "Perfect quick meal after a long day",
            },
        ],
        tips: ["Start early to avoid crowds", "Wear comfortable walking shoes", "Bring water and snacks"],
    },
    // Day 6 - Latin Quarter & Panthéon
    {
        dayNumber: 6,
        date: "Saturday, July 20, 2024",
        title: "Latin Quarter & Intellectual Paris",
        weather: {
            temperature: "24°C / 75°F",
            condition: "Partly cloudy",
            recommendation: "Perfect for walking and exploring",
        },
        budget: { total: 500, meals: 210, activities: 190, transport: 100 },
        activities: [
            {
                time: "8:30 AM",
                title: "Breakfast at Café Procope",
                description: "Historic café frequented by Voltaire and Napoleon",
                type: "dining",
                duration: "1 hour",
                location: "13 Rue de l'Ancienne Comédie, 6th Arrondissement",
                tips: "Oldest café in Paris with incredible history",
            },
            {
                time: "10:00 AM",
                title: "Panthéon",
                description: "Mausoleum of famous French figures including Curie and Voltaire",
                type: "sightseeing",
                duration: "1.5 hours",
                location: "Place du Panthéon, 5th Arrondissement",
                tips: "Don't miss the Foucault Pendulum demonstration",
            },
            {
                time: "12:00 PM",
                title: "Latin Quarter Walking Tour",
                description: "Medieval streets, Sorbonne University, and bookshops",
                type: "cultural",
                duration: "2 hours",
                location: "5th Arrondissement",
                tips: "Visit Shakespeare and Company bookstore",
            },
            {
                time: "2:30 PM",
                title: "Lunch at Le Procope",
                description: "Traditional French cuisine in historic setting",
                type: "dining",
                duration: "1.5 hours",
                location: "13 Rue de l'Ancienne Comédie, 6th Arrondissement",
                tips: "Try the coq au vin and crème brûlée",
            },
            {
                time: "4:30 PM",
                title: "Sainte-Chapelle",
                description: "Gothic chapel famous for stunning stained glass windows",
                type: "sightseeing",
                duration: "1 hour",
                location: "8 Boulevard du Palais, 1st Arrondissement",
                tips: "Visit on a sunny day for best stained glass effect",
            },
            {
                time: "6:00 PM",
                title: "Notre-Dame Exterior & Île de la Cité",
                description: "Explore the island and cathedral exterior (under restoration)",
                type: "sightseeing",
                duration: "1 hour",
                location: "Île de la Cité, 4th Arrondissement",
                tips: "Walk around the entire island for different perspectives",
            },
            {
                time: "7:30 PM",
                title: "Aperitif at Harry's Bar",
                description: "Historic American bar, birthplace of the Bloody Mary",
                type: "dining",
                duration: "1 hour",
                location: "5 Rue Daunou, 2nd Arrondissement",
                tips: "Try their famous cocktails and bar snacks",
            },
            {
                time: "9:00 PM",
                title: "Farewell Dinner at Le Grand Véfour",
                description: "Michelin-starred restaurant for a special final night",
                type: "dining",
                duration: "2.5 hours",
                location: "17 Rue de Beaujolais, 1st Arrondissement",
                tips: "Book well in advance; dress code required",
            },
        ],
        tips: ["Book restaurant reservations early", "Combine nearby attractions", "Save energy for special dinner"],
    },
    // Day 7 - Departure
    {
        dayNumber: 7,
        date: "Sunday, July 21, 2024",
        title: "Au Revoir Paris",
        weather: { temperature: "22°C / 72°F", condition: "Clear", recommendation: "Perfect final day" },
        budget: { total: 400, meals: 150, activities: 100, transport: 150 },
        activities: [
            {
                time: "8:00 AM",
                title: "Farewell Breakfast at Breizh Café",
                description: "Modern crêperie for a final French breakfast",
                type: "dining",
                duration: "1 hour",
                location: "109 Rue Vieille du Temple, 3rd Arrondissement",
                tips: "Try both sweet and savory crêpes",
            },
            {
                time: "10:00 AM",
                title: "Check-out & Luggage Storage",
                description: "Check out of hotel and store luggage",
                type: "accommodation",
                duration: "30 minutes",
                location: "Hotel des Grands Boulevards",
                tips: "Confirm luggage pickup time and airport transfer",
            },
            {
                time: "11:00 AM",
                title: "Last-Minute Shopping at Galeries Lafayette",
                description: "Iconic department store for souvenirs and French goods",
                type: "shopping",
                duration: "2 hours",
                location: "40 Boulevard Haussmann, 9th Arrondissement",
                tips: "Don't miss the beautiful Art Nouveau dome",
            },
            {
                time: "1:30 PM",
                title: "Final Lunch at L'Ami Jean",
                description: "Return to favorite bistro for last meal",
                type: "dining",
                duration: "1.5 hours",
                location: "27 Rue Malar, 7th Arrondissement",
                tips: "Order your favorite dishes from the week",
            },
            {
                time: "3:30 PM",
                title: "Collect Luggage & Airport Transfer",
                description: "RER B train to Charles de Gaulle Airport",
                type: "transport",
                duration: "1.5 hours",
                location: "Hotel to CDG Airport",
                tips: "Allow extra time for international departure procedures",
            },
            {
                time: "6:00 PM",
                title: "Departure Flight to New York",
                description: "Air France flight AF007 to JFK",
                type: "transport",
                duration: "8 hours",
                location: "CDG Terminal 2E",
                tips: "Arrive 3 hours early for international flights",
            },
        ],
        tips: ["Pack the night before", "Keep receipts for tax refunds", "Exchange remaining euros"],
    },
];
export const exampleData = {
    userPreferences: {
        homeLocation: "New York, NY",
        startDate: "2024-07-15",
        endDate: "2024-07-22",
        budget: 3500, // Corrected from budgetValue
        travelPace: "Explorer", // Corrected from travelStyle
        travelGroup: "Couple",
        adults: 2,
        children: 0,
        interests: ["Food & Dining", "History & Culture", "Arts & Entertainment"],
        numberOfDays: 8,
    },
    selectedDestination: {
        id: 1,
        title: "Paris, France",
        city: "Paris",
        country: "France",
        subtitle: "The City of Light - Perfect for culture and cuisine lovers",
        price: 2650,
        matchScore: 95,
        flag: "🇫🇷",
    },
    selectedRoute: {
        id: 2,
        title: "High-Speed Train",
        type: "train",
        duration: "6h 30m",
        price: 2275,
        carbonFootprint: "0.2 tons CO2",
    },
    detailedSchedule: [
        {
            dayNumber: 1,
            date: "Monday, July 15, 2024",
            title: "Welcome to Paris",
            weather: { temperature: "24°C / 75°F", condition: "Sunny" },
            activities: [
                { time: "10:00 AM", title: "Arrive at CDG Airport", type: "transport", location: "CDG Airport" },
                { time: "2:00 PM", title: "Check-in at Hotel des Grands Boulevards", type: "accommodation", location: "2nd Arrondissement" },
                { time: "3:30 PM", title: "Welcome Lunch at L'Ami Jean", type: "dining", location: "7th Arrondissement" },
                { time: "5:30 PM", title: "Seine River Walk", type: "activity", location: "From Pont Neuf" },
                { time: "8:00 PM", title: "Dinner at Le Comptoir du Relais", type: "dining", location: "6th Arrondissement" },
            ],
        },
        {
            dayNumber: 2,
            date: "Tuesday, July 16, 2024",
            title: "Eiffel Tower and Louvre",
            activities: [
                { time: "9:00 AM", title: "Visit the Eiffel Tower", type: "sightseeing", location: "Champs de Mars" },
                { time: "12:00 PM", title: "Lunch near the Louvre", type: "dining", location: "1st Arrondissement" },
                { time: "2:00 PM", title: "Louvre Museum Tour", type: "cultural", location: "Louvre" },
                { time: "7:00 PM", title: "Dinner and Wine Tasting", type: "dining", location: "Marais" },
            ],
        },
    ],
};
export const steps = [
    {number: 1, title: "Home Location", description: "Where are you traveling from?"},
    {number: 2, title: "Travelers", description: "Who's traveling?"},
    {number: 3, title: "Dates & Budget", description: "When and how much?"},
    {number: 4, title: "Interests", description: "What do you enjoy?"},
]
export const travelInterests = [
    {
        id: "Food",
        icon: "🍽️",
        title: "Food & Dining",
        description: "Local cuisine and restaurants"
    },
    {
        id: "History",
        icon: "🏛️",
        title: "History & Culture",
        description: "Museums and historical sites",
    },
    {
        id: "Arts",
        icon: "🎨",
        title: "Arts & Entertainment",
        description: "Galleries, shows, and events",
    },
    {
        id: "Nature",
        icon: "🏞️",
        title: "Nature & Outdoors",
        description: "Parks, hiking, and wildlife"
    },
    {
        id: "Shopping",
        icon: "🛍️",
        title: "Shopping",
        description: "Markets, malls, and boutiques"
    },
    {
        id: "Nightlife",
        icon: "🌙",
        title: "Nightlife",
        description: "Bars, clubs, and evening entertainment",
    },
]
export const travelGroups = [
    {id: "Solo", icon: "👤", title: "Solo"},
    {id: "Couple", icon: "👫", title: "Couple"},
    {id: "Family", icon: "👨‍👩‍👧‍👦", title: "Family"},
    {id: "Friends", icon: "👥", title: "Friends"},
]

export const properties = [
    {
        name: "Home Location",
        image: "🏠"
    },
    {
        name: "Travel Dates",
        image: "📅",

    },
    {
        name: "Budget",
        image: "💰",

    },
    {
        name: "Interests",
        image: "❤️"
    }
];
export const tabs = [
    { id: "overview", label: "📊 Overview", icon: "📊" },
    { id: "schedule", label: "📅 Daily TabSchedule", icon: "📅" },
    { id: "transport", label: "🚄 Transportation", icon: "🚄" }
];

export const beforeYouGo = [
    {
        task: "Digital Documentation",
        description: `Digitize everything. Take photos or scans of your passport, visa, and reservations. Store these securely in a password manager or a cloud service like Google Drive, and also have physical copies in a separate bag from the originals.`,
        isDone: false,
        emoji: "📱",
    },
    {
        task: "Stay Connected",
        description: `Research and purchase an eSIM for your destination, or check your phone provider for a suitable plan. Activate it before you leave so you have data the moment you land.`,
        isDone: false,
        emoji: "🌐",
    },
    {
        task: "Smart Financials",
        description: `Notify your bank of travel plans via their app. Consider using a multi-currency card and have a backup credit card along with some local currency.`,
        isDone: false,
        emoji: "💳",
    },
    {
        task: "Travel Apps",
        description: `Download essential apps: TripIt for itineraries, Google Maps for offline navigation, Google Translate for language, and Rome2Rio for local transport.`,
        isDone: false,
        emoji: "🗺️",
    },
    {
        task: "Cybersecurity",
        description: `Install a VPN on your devices to protect your data on public Wi-Fi. Use a password manager and back up your data before you go.`,
        isDone: false,
        emoji: "🔒",
    },
];

export const duringYourTrip = [
    {
        task: "Digital Security",
        description: `Be cautious of public Wi-Fi. Use a VPN and avoid logging into sensitive accounts. Enable strong passwords and multi-factor authentication on your devices.`,
        isDone: false,
        emoji: "🛡️",
    },
    {
        task: "Navigating your Destination",
        description: `Use your pre-downloaded offline maps. Use your phone's digital wallet for quick and secure purchases, but have a physical card and cash as a backup.`,
        isDone: false,
        emoji: "🧭",
    },
    {
        task: "Health and Safety",
        description: `Save local emergency numbers and your home country's embassy contact info. Share your live location with a trusted contact and stay informed about local news.`,
        isDone: false,
        emoji: "🚨",
    },
    {
        task: "Embrace the Local Experience",
        description: `Use local food and transport apps. Look for authentic recommendations from locals and be open to new experiences.`,
        isDone: false,
        emoji: "🍜",
    },
    {
        task: "Sustainable Travel",
        description: `Carry a reusable water bottle to reduce plastic waste and support local businesses, restaurants, and artisans to help the local economy.`,
        isDone: false,
        emoji: "♻️",
    },
];


